library("DESeq2")
data<-read.table("0-200M_counts-normalized.txt", sep="\t", header = T, row.names = 1)
data1=data[ ,c(1,2,3,4,5,6)]
condition=factor(c(rep("0",3),rep("200",3)))
coldata<-data.frame(row.names = colnames(data1),condition) 
dds<-DESeqDataSetFromMatrix(countData = data1,colData = coldata,design =~ condition)
colData(dds)$condition<-factor(colData(dds)$condition,level=c('0','200'))
sizeFactors(dds)<-c(1,1,1,1,1,1)
dds<- estimateDispersions(dds)
dds <- nbinomWaldTest(dds)
res<-results(dds)
resdata<-merge(as.data.frame(res),as.data.frame(counts(dds,normalized=TRUE)),by="row.names",sort=FALSE)
resdata$significant<-as.factor(resdata$padj<0.05&abs(resdata$log2FoldChange)>1)
write.csv(resdata,file="0-200-DEG.csv",row.names = F)
quit()
